if(EXISTS "E:/rk3568/project/myproject/assitant/build-host/tests/test_moonlight_adapter[1]_tests.cmake")
  include("E:/rk3568/project/myproject/assitant/build-host/tests/test_moonlight_adapter[1]_tests.cmake")
else()
  add_test(test_moonlight_adapter_NOT_BUILT test_moonlight_adapter_NOT_BUILT)
endif()
