if(EXISTS "E:/rk3568/project/myproject/assitant/build-host/tests/test_image_rb[1]_tests.cmake")
  include("E:/rk3568/project/myproject/assitant/build-host/tests/test_image_rb[1]_tests.cmake")
else()
  add_test(test_image_rb_NOT_BUILT test_image_rb_NOT_BUILT)
endif()
