if(EXISTS "E:/rk3568/project/myproject/assitant/build-host/tests/test_preprocess[1]_tests.cmake")
  include("E:/rk3568/project/myproject/assitant/build-host/tests/test_preprocess[1]_tests.cmake")
else()
  add_test(test_preprocess_NOT_BUILT test_preprocess_NOT_BUILT)
endif()
